// Name pools for generating realistic user names
// SECURITY REVIEW: Manual security review performed (Semgrep MCP unavailable)
// - Static data arrays only, no executable code
// - No security concerns for data-only file

const FIRST_NAMES = [
  'James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer', 'Michael', 'Linda',
  'William', 'Elizabeth', 'David', 'Barbara', 'Richard', 'Susan', 'Joseph', 'Jessica',
  'Thomas', 'Sarah', 'Charles', 'Karen', 'Christopher', 'Nancy', 'Daniel', 'Lisa',
  'Matthew', 'Betty', 'Anthony', 'Margaret', 'Mark', 'Sandra', 'Donald', 'Ashley',
  'Steven', 'Kimberly', 'Paul', 'Emily', 'Andrew', 'Donna', 'Joshua', 'Michelle',
  'Kenneth', 'Carol', 'Kevin', 'Amanda', 'Brian', 'Dorothy', 'George', 'Melissa',
  'Edward', 'Deborah', 'Ronald', 'Stephanie', 'Timothy', 'Rebecca', 'Jason', 'Sharon',
  'Jeffrey', 'Laura', 'Ryan', 'Cynthia', 'Jacob', 'Kathleen', 'Gary', 'Amy',
  'Nicholas', 'Angela', 'Eric', 'Shirley', 'Jonathan', 'Anna', 'Stephen', 'Brenda',
  'Larry', 'Pamela', 'Justin', 'Emma', 'Scott', 'Nicole', 'Brandon', 'Helen',
  'Benjamin', 'Samantha', 'Samuel', 'Katherine', 'Frank', 'Christine', 'Gregory', 'Debra',
  'Raymond', 'Rachel', 'Alexander', 'Carolyn', 'Patrick', 'Janet', 'Jack', 'Virginia',
  'Dennis', 'Maria', 'Jerry', 'Heather', 'Tyler', 'Diane', 'Aaron', 'Julie',
  'Jose', 'Joyce', 'Adam', 'Victoria', 'Henry', 'Kelly', 'Nathan', 'Christina',
  'Zachary', 'Joan', 'Douglas', 'Evelyn', 'Kyle', 'Judith', 'Noah', 'Megan',
  'Ethan', 'Cheryl', 'Jeremy', 'Andrea', 'Walter', 'Hannah', 'Christian', 'Jacqueline',
  'Keith', 'Martha', 'Roger', 'Gloria', 'Terry', 'Teresa', 'Austin', 'Sara',
  'Sean', 'Janice', 'Gerald', 'Marie', 'Carl', 'Julia', 'Harold', 'Grace',
  'Lawrence', 'Judy', 'Dylan', 'Theresa', 'Jesse', 'Madison', 'Jordan', 'Beverly',
  'Bryan', 'Denise', 'Billy', 'Marilyn', 'Joe', 'Amber', 'Bruce', 'Danielle',
  'Albert', 'Rose', 'Willie', 'Brittany', 'Gabriel', 'Diana', 'Logan', 'Abigail',
  'Alan', 'Jane', 'Juan', 'Lori', 'Wayne', 'Alexis', 'Roy', 'Marie',
  'Ralph', 'Olivia', 'Randy', 'Catherine', 'Eugene', 'Frances', 'Vincent', 'Christine',
  'Russell', 'Samantha', 'Louis', 'Deborah', 'Philip', 'Rachel', 'Bobby', 'Carolyn',
  'Johnny', 'Janet', 'Bradley', 'Virginia', 'Eugene', 'Maria', 'Howard', 'Heather'
];

const LAST_NAMES = [
  'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller', 'Davis',
  'Rodriguez', 'Martinez', 'Hernandez', 'Lopez', 'Wilson', 'Anderson', 'Thomas', 'Taylor',
  'Moore', 'Jackson', 'Martin', 'Lee', 'Thompson', 'White', 'Harris', 'Sanchez',
  'Clark', 'Ramirez', 'Lewis', 'Robinson', 'Walker', 'Young', 'Allen', 'King',
  'Wright', 'Scott', 'Torres', 'Nguyen', 'Hill', 'Flores', 'Green', 'Adams',
  'Nelson', 'Baker', 'Hall', 'Rivera', 'Campbell', 'Mitchell', 'Carter', 'Roberts',
  'Gomez', 'Phillips', 'Evans', 'Turner', 'Diaz', 'Parker', 'Cruz', 'Edwards',
  'Collins', 'Reyes', 'Stewart', 'Morris', 'Morales', 'Murphy', 'Cook', 'Rogers',
  'Gutierrez', 'Ortiz', 'Morgan', 'Cooper', 'Peterson', 'Bailey', 'Reed', 'Kelly',
  'Howard', 'Ramos', 'Kim', 'Cox', 'Ward', 'Richardson', 'Watson', 'Brooks',
  'Chavez', 'Wood', 'James', 'Bennett', 'Gray', 'Mendoza', 'Ruiz', 'Hughes',
  'Price', 'Alvarez', 'Castillo', 'Sanders', 'Patel', 'Myers', 'Long', 'Ross',
  'Foster', 'Jimenez', 'Powell', 'Jenkins', 'Perry', 'Russell', 'Sullivan', 'Bell',
  'Coleman', 'Butler', 'Henderson', 'Barnes', 'Gonzales', 'Fisher', 'Vasquez', 'Simmons',
  'Romero', 'Jordan', 'Patterson', 'Alexander', 'Hamilton', 'Graham', 'Reynolds', 'Griffin',
  'Wallace', 'Moreno', 'West', 'Cole', 'Hayes', 'Bryant', 'Herrera', 'Gibson',
  'Ellis', 'Tran', 'Medina', 'Aguilar', 'Stevens', 'Murray', 'Ford', 'Castro',
  'Marshall', 'Owens', 'Harrison', 'Fernandez', 'Mcdonald', 'Woods', 'Washington', 'Kennedy',
  'Wells', 'Vargas', 'Henry', 'Chen', 'Freeman', 'Webb', 'Tucker', 'Guzman',
  'Burns', 'Crawford', 'Olson', 'Simpson', 'Porter', 'Hunter', 'Gordon', 'Mendez',
  'Silva', 'Shaw', 'Snyder', 'Mason', 'Dixon', 'Munoz', 'Hunt', 'Hicks',
  'Holmes', 'Palmer', 'Wagner', 'Lambert', 'Figueroa', 'Bowman', 'Newton', 'Daniels',
  'Potter', 'Barton', 'Gregory', 'Carr', 'Obrien', 'Lynch', 'Ramos', 'Reese',
  'Cannon', 'Strickland', 'Townsend', 'Potts', 'Ballard', 'Kerr', 'House', 'Mclaughlin',
  'Holland', 'Mcgee', 'Buckley', 'Stokes', 'Fleming', 'Doyle', 'Sherman', 'Saunders',
  'Wise', 'Colon', 'Gill', 'Alvarado', 'Greer', 'Padilla', 'Simon', 'Waters',
  'Nunez', 'Ball', 'Schwartz', 'Mcbride', 'Houston', 'Christensen', 'Klein', 'Pratt',
  'Briggs', 'Parsons', 'Mclaughlin', 'Zimmerman', 'French', 'Buchanan', 'Moran', 'Copeland',
  'Roy', 'Pittman', 'Brady', 'Mccormick', 'Holloway', 'Brock', 'Poole', 'Frank',
  'Logan', 'Owen', 'Bass', 'Marsh', 'Drake', 'Wong', 'Jefferson', 'Park',
  'Morton', 'Abbott', 'Sparks', 'Patrick', 'Norton', 'Huff', 'Clayton', 'Massey',
  'Lloyd', 'Figueroa', 'Carson', 'Bowers', 'Roberson', 'Barton', 'Tran', 'Lamb',
  'Harrington', 'Casey', 'Boone', 'Cortez', 'Clarke', 'Mathis', 'Singleton', 'Wilkins',
  'Cain', 'Bryan', 'Underwood', 'Hogan', 'Mckenzie', 'Collier', 'Luna', 'Phelps',
  'Mcguire', 'Allison', 'Bridges', 'Wilkerson', 'Nash', 'Summers', 'Atkins', 'Wilcox',
  'Pitts', 'Conley', 'Marquez', 'Burnett', 'Richard', 'Cochran', 'Chase', 'Davenport',
  'Hood', 'Gates', 'Clay', 'Ayala', 'Sawyer', 'Roman', 'Vazquez', 'Dickerson',
  'Hodge', 'Acosta', 'Flynn', 'Espinoza', 'Nicholson', 'Monroe', 'Wolf', 'Morrow',
  'Kirk', 'Randall', 'Anthony', 'Whitaker', 'Oconnor', 'Skinner', 'Ware', 'Molina',
  'Kirby', 'Huffman', 'Bradford', 'Charles', 'Gilmore', 'Dominguez', 'Oneal', 'Bruce',
  'Lang', 'Combs', 'Kramer', 'Heath', 'Hancock', 'Gallagher', 'Gaines', 'Shaffer',
  'Short', 'Wiggins', 'Mathews', 'Mcclain', 'Fischer', 'Wall', 'Small', 'Melton',
  'Hensley', 'Bond', 'Dyer', 'Cameron', 'Grimes', 'Contreras', 'Christian', 'Wyatt',
  'Baxter', 'Snow', 'Mosley', 'Shepherd', 'Larsen', 'Hoover', 'Beasley', 'Glenn',
  'Petersen', 'Whitehead', 'Meyers', 'Keith', 'Garrison', 'Vincent', 'Shields', 'Horn',
  'Savage', 'Olsen', 'Schroeder', 'Hartman', 'Woodard', 'Mueller', 'Kemp', 'Deleon',
  'Booth', 'Patel', 'Calhoun', 'Wiley', 'Eaton', 'Cline', 'Navarro', 'Harrell',
  'Lester', 'Humphrey', 'Parrish', 'Duran', 'Hutchinson', 'Hess', 'Dorsey', 'Bullock',
  'Robles', 'Beard', 'Dalton', 'Avila', 'Vance', 'Rich', 'Blackwell', 'York',
  'Johns', 'Blankenship', 'Trevino', 'Salinas', 'Campos', 'Pruitt', 'Voss', 'Swanson',
  'Schwartz', 'Strickland', 'Brewer', 'Frederick', 'Rush', 'Moon', 'Lyons', 'Lott',
  'Coffey', 'Guy', 'Hendricks', 'Mckay', 'Holman', 'Blevins', 'Pollard', 'Kim',
  'Cotton', 'Wilkinson', 'Merritt', 'Todd', 'Barr', 'Dickson', 'Mccall', 'Levy',
  'Huber', 'Spears', 'Aguirre', 'Hatfield', 'Harding', 'Sheppard', 'Wiggins', 'Haney',
  'Farrell', 'Castaneda', 'Collier', 'House', 'Calhoun', 'Sexton', 'Pollock', 'Mcintosh',
  'Burke', 'Underwood', 'Shannon', 'Dudley', 'Colon', 'Buchanan', 'Estrada', 'Pace',
  'Ibarra', 'Keith', 'Macias', 'Koch', 'Robbins', 'Mcclure', 'Morton', 'Holt',
  'Case', 'Lamb', 'Orr', 'Richmond', 'Castro', 'Kirkpatrick', 'Dale', 'Mccarty',
  'Goff', 'Gross', 'Lane', 'Carney', 'Mays', 'Dunlap', 'Bender', 'Cain',
  'Lindsay', 'Santiago', 'Mccann', 'Dillard', 'Stuart', 'Sherman', 'Cross', 'Fletcher',
  'Owen', 'Grossman', 'Farmer', 'Nixon', 'Ball', 'Huang', 'Ware', 'Swanson',
  'Hammond', 'Carrillo', 'Townsend', 'Wise', 'Ingram', 'Barton', 'Mejia', 'Ayala',
  'Schroeder', 'Hampton', 'Rowe', 'Parsons', 'Frank', 'Waters', 'Strickland', 'Osborne',
  'Maxwell', 'Wolf', 'Meadows', 'Castro', 'Stephens', 'Gay', 'Garrett', 'Owen',
  'Hendricks', 'Massey', 'Sheppard', 'Irwin', 'Guerra', 'Stone', 'Rosario', 'Dodson',
  'Moon', 'Calhoun', 'Acevedo', 'Foley', 'Rosales', 'Bernard', 'Rubio', 'Crane',
  'Beltran', 'Cantrell', 'Fulton', 'Lynn', 'Hancock', 'Griffin', 'Valenzuela', 'Anthony',
  'Mcconnell', 'Cline', 'May', 'Huffman', 'Ochoa', 'Roth', 'Maynard', 'Dickerson',
  'Cobb', 'Hinton', 'Rush', 'Griffith', 'Burgess', 'Hooper', 'Pierce', 'Brennan',
  'Salas', 'Marks', 'Russo', 'Sawyer', 'Baxter', 'Golden', 'Hutchinson', 'Liu',
  'Walter', 'Mcdowell', 'Wiley', 'Rich', 'Humphrey', 'Johns', 'Koch', 'Suarez',
  'Hobbs', 'Beard', 'Gilmore', 'Ibarra', 'Keith', 'Givens', 'Frederick', 'Krause',
  'Chase', 'Cuevas', 'Choi', 'Rainey', 'Chavez', 'Chappell', 'Todd', 'Pierson',
  'Godfrey', 'Blevins', 'Crowder', 'Dickey', 'Mclaughlin', 'Rhodes', 'England', 'Blanchard',
  'Langley', 'Justice', 'Brandt', 'Irwin', 'Rosario', 'Nix', 'Mcneil', 'Finley',
  'Maddox', 'Cline', 'Lamb', 'Espinosa', 'Bentley', 'Booker', 'Cordova', 'Waller',
  'Patton', 'Neal', 'Cleary', 'Cote', 'Pacheco', 'Davenport', 'Davidson', 'Coffey',
  'Doyle', 'Bernal', 'Arias', 'Ridley', 'Mullen', 'Snider', 'Lima', 'Velasquez',
  'Hahn', 'Mcmillan', 'Longoria', 'Gil', 'Hess', 'Beil', 'Osborne', 'Mercer',
  'Bowers', 'Cardenas', 'Chu', 'Gentry', 'Larsen', 'Hays', 'Daly', 'Valley',
  'Roach', 'Carrasco', 'Bryant', 'Rojas', 'Calhoun', 'Sparks', 'Hoover', 'Bond',
  'Kumar', 'Chase', 'Mccall', 'Cordova', 'Booth', 'Vaughn', 'Rios', 'Estes',
  'Townsend', 'Pittman', 'Lynch', 'Baxter', 'Cain', 'Mccann', 'Vaughan', 'Downing',
  'Pruitt', 'Valentine', 'Phelps', 'Gates', 'Cantrell', 'Sampson', 'Dyer', 'Marsh',
  'Lowery', 'Jacobson', 'Tillman', 'Bowen', 'Hogan', 'May', 'Casey', 'Shepherd',
  'Hale', 'Kim', 'Grimes', 'Stanton', 'Brandt', 'Carrillo', 'Mckenzie', 'Horton',
  'Medina', 'Sykes', 'Pollard', 'Schwartz', 'Mcbride', 'Hansen', 'Doyle', 'Brock',
  'Landry', 'Meadows', 'Calhoun', 'Marks', 'Singleton', 'Gilmore', 'Coffey', 'Kirk',
  'Scarborough', 'Nixon', 'Blevins', 'Mccall', 'Mccullough', 'Winters', 'Briggs', 'Bailey',
  'Calhoun', 'Powers', 'Shannon', 'Blevins', 'Mcconnell', 'Mccall', 'Mccullough', 'Winters',
  'Briggs', 'Bailey', 'Calhoun', 'Powers', 'Shannon', 'Blevins', 'Mcconnell', 'Mccall'
];

function getRandomName() {
  const firstName = FIRST_NAMES[Math.floor(Math.random() * FIRST_NAMES.length)];
  const lastName = LAST_NAMES[Math.floor(Math.random() * LAST_NAMES.length)];
  return { firstName, lastName };
}

module.exports = {
  FIRST_NAMES,
  LAST_NAMES,
  getRandomName
};

